version: '3.9'

services:
  curado-fibra:

    container_name: curado-fibra

    build: .

    restart: unless-stopped

    ports:
      - "3010:3000"

    volumes:
      - ./data:/app/data
        ./home/industrial/scada/pdfs:/app/pdfs

    environment:
      TZ: America/Argentina/Buenos_Aires
      ADMIN_USER: admin
      ADMIN_PASS: 1234
      SESSION_SECRET: clave_super_secreta_2026
      PORT: 3000
