version: '3.9'

services:
  curado-fibra:

    container_name: curado-fibra

    build: .

    restart: unless-stopped

    ports:
      - "3010:3000"

    volumes:
      - datos_curado_fibra:/app/data
      - pdfs_curado_fibra:/app/pdfs
      - backups_curado_fibra:/app/backups

    environment:
      TZ: America/Argentina/Buenos_Aires
      ADMIN_USER: admin
      ADMIN_PASS: 1234
      SESSION_SECRET: clave_super_secreta_2026
      PORT: 3000

volumes:
  datos_curado_fibra:
  pdfs_curado_fibra:
  backups_curado_fibra:
